name: GitHub Page

on:
    push:
        branches:
            - main # main 更新触发

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: true # clone submodules
                  fetch-depth: 0 # 克隆所有历史信息

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "0.126.1" # Hugo 版本
                  extended: true # hugo插件版 Stack主题 必须启用

            - name: Cache resources # 缓存 resource 文件加快生成速度
              uses: actions/cache@v3
              with:
                  path: resources
                  # 检查照片文件变化
                  key: ${{ runner.os }}-hugocache-${{ hashFiles('content/**/*') }}
                  restore-keys: ${{ runner.os }}-hugocache-

            - name: 部署到Github
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  token: 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
                  repository-name: kevinwu06/blog
                  branch: main
                  folder: public
                  commit-message: "${{ github.event.head_commit.message }} Updated By Github Actions"
                
